apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleet-management

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - istio/virtualservice.yaml
  - istio/destinationrule.yaml
  - istio/gateway.yaml
  - istio/peerauthentication.yaml
  - istio/authorizationpolicy.yaml
  - istio/serviceentry.yaml

commonLabels:
  app.kubernetes.io/name: fleet-frontend
  app.kubernetes.io/part-of: fleet-management
  app.kubernetes.io/managed-by: kustomize

images:
  - name: fleet-frontend
    newName: harinejan/fleet-frontend
    newTag: latest

